### PR TITLE
fixed stacking item glitch(bug)

### PR DESCRIPTION
**Pull request by miladm78**

### CODE REVIEW

**Comment by Mrcomputer1** [comment]
I just want to check that setting this pull request to draft was intentional, since there hasn't been any activity on it for about a week? If it was intentional, that is fine.

**Comment by MiKDev** [comment]
this glitch found by players on our server and Milad fix that, I suggested him to make PR to main repo to fixing this in next official version.
we also find bug that players who add Items in their enderchest and when candidate them for sale, after buying it by another player, item still exists in enderchest.

**Comment by Mrcomputer1** [comment]
Is there a reason this pull request is marked as draft/work in progress? Since there hasn't been any commits added in two weeks, I'm going to assume it was accidentally marked draft/work in progress. I will review/merge the pull request and, if needed, make any fixes, tomorrow.

> this glitch found by players on our server and Milad fix that, I suggested him to make PR to main repo to fixing this in next official version.

Ok, thank you.

>  we also find bug that players who add Items in their enderchest and when candidate them for sale, after buying it by another player, item still exists in enderchest.

Hmm.. I will see if I can reproduce and fix that issue.

**Comment by MiKDev** [comment]
We were overload to update our infrastructure, we also add tax for over 5 emerald purchase, for this reason Milad tagged PR as work/draft, for any global patch we will create new PR.
Thank you for your notification.

**Pull request merged**
